### ISSUE TITLE
Hook failed to identify unencrypted secret

### ISSUE THREAD

**Issue by adtennant** [k8s-at-home/sops-pre-commit#5] opened 2021-04-23 17:37 UTC
The hook failed to flag `additional-scrape-configs.yaml` ~~in this recent commit:
https://github.com/adtennant/homelab/commit/cff74e955c96ee0c89a764421fad8c5d3454491f~~

For now I can reproduce with:
```
git clone git@github.com:adtennant/homelab.git
cd homelab
pre-commit install
cp k8s/core/prometheus/additional-scrape-configs.yaml .
git commit -am "Test commit."
```

Alternatively:

```
git clone git@github.com:adtennant/homelab.git
cd homelab
pre-commit run --all-files
```

I would expect the newly copied additional-scrape-configs.yaml to trigger the hook in the first case, the original k8s/core/prometheus/additional-scrape-configs.yaml in the second.

**Comment by adtennant** [comment] 2021-04-23 18:28
I've managed to trigger this behaviour multiple times now. I can't share the files though as they were meant to be encrypted, unlike the above example.

**Comment by onedr0p** [comment] 2021-04-23 18:47
Can you share more examples, maybe by replacing the secret with random text?

What version of the hook are you using?

**Comment by adtennant** [comment] 2021-04-24 09:47
v2.0.2

I'll try and create a minimal, reproducable example repo later today.

For now I can reproduce with:
```
git clone git@github.com:adtennant/homelab.git
cd homelab
pre-commit install
cp k8s/core/prometheus/additional-scrape-configs.yaml .
git commit -am "Test commit."
```

Alternatively:
```
git clone git@github.com:adtennant/homelab.git
cd homelab
pre-commit run --all-files
```

I would expect the newly copied `additional-scrape-configs.yaml` to trigger the hook in the first case, the original `k8s/core/prometheus/additional-scrape-configs.yaml` in the second.

**Comment by bjw-s** [comment] 2021-04-24 09:55
I'm _guessing_ it's caused by the dot in the key, that trips up some yaml processors.
Will try to investigate that some more later

**Comment by onedr0p** [comment] 2021-04-24 11:58
@bjw-s the hook only uses regex, no YAML lib is used.

@adtennant it's hard to see what the issue is now that your repo is gone, please post the secrets (change the secret data) that were not caught by the hook, and we can help debug the issue. Right now it's impossible to debug any issue you are having.

**Comment by bjw-s** [comment] 2021-04-24 12:11
https://github.com/adtennant/homelab/blob/master/k8s/core/prometheus/additional-scrape-configs.yaml

This is the file in question, right?

**Comment by adtennant** [comment] 2021-04-24 12:22
Whilst the commit linked in the original comment doesn't exist (due to subsequent commits containing secret data), the repo still exists and is public.

**Comment by adtennant** [comment] 2021-04-24 12:23
@bjw-s Yes, that is the file. Although I can't get the hook to trigger for any secret in that repo (when unencrypted).

**Comment by onedr0p** [comment] 2021-04-24 12:27
I have identified the problem, working on a fix.

**Comment by onedr0p** [comment] 2021-04-24 12:34
Fixed in https://github.com/k8s-at-home/sops-pre-commit/releases/tag/v2.0.3

Thanks for reporting!

**Closed as completed by onedr0p** 2021-04-24 12:34 UTC
Labels: bug

**Comment by adtennant** [comment] 2021-04-24 12:35
Thanks for fixing so quickly. Sorry for the poor quality of the initial report, it was an end of the day find.

**Comment by onedr0p** [comment] 2021-04-24 12:36
No worries, if I only tested it I would have seen it was not working at all. Silly python regex.
